version: '3.7'

services:
  mssql-server-linux:
    hostname: mssql-server-linux
    build: 
      context: .
      dockerfile: dockerfile
    user: root
    ports:  
      - "1433:1433"
    env_file:
      - sqlserver.env
      - sapassword.env
    volumes: 
      - sqlsystem:/var/opt/mssql/
      - sqldata:/var/opt/sqlserver/data
      - sqllog:/var/opt/sqlserver/log
      - sqlbackup:/var/opt/sqlserver/backup
volumes:
  sqlsystem:
  sqldata:
  sqllog:
  sqlbackup: